# .github/workflows/lint.yml

on:
#  push:
  pull_request:
  workflow_dispatch:

name: PHP Code Standard Fixer (Dry Run)
jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: PHP-CS-Fixer
      uses: docker://oskarstark/php-cs-fixer-ga
      with:
        args: --config=.php-cs-fixer.php --diff --dry-run
