#name, main, version and api are required
name: HyundaiCommando
main: keopiwauyu\HyundaiCommando\MainClass
version: 0.2.1
api: 4.0.0

load: POSTWORLD
author: 커피와 우유
description: command wha to type? ok, chat box shkw u
website: https://github.com/Keopiwauyu/HyundaiCommando
commands:
  commando:
    description: command wha to type? ok, chat box shkw u
    usage: "/commando"
    permission: hyundai.commando
permissions:
  hyundai.commando:
    description: command wha to type? ok, chat box shkw u
    default: true
