on:
  workflow_dispatch:

name: Create PRs for php-cs-fixer fixups

jobs:
    fix-cs:
        name: Fix CS violations
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3  
            - uses: docker://oskarstark/php-cs-fixer-ga:latest
              with:
                args: --config=.php-cs-fixer.php --diff
            - uses: peter-evans/create-pull-request@v4
              id: cpr
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: Apply php-cs-fixer changes as of ${{ github.sha }}
                  title: Fix coding standards in ${{ github.ref }}
                  branch: php-cs-fixer/${{ github.ref }}
                  assignees: ${{ github.actor }}
                  labels: php-cs-fixer
                  body: |
                    Please apply these changes on the ${{ github.ref }} branch to fix coding standard violations.
