on:
  pull_request:
    types: [closed]

name: Create PRs for php-cs-fixer fixups after a PR is merged

jobs:
    fix-cs:
        name: Fix CS violations for merged PR
        runs-on: ubuntu-latest
        if: github.event.pull_request.merged == true
        steps:
            - uses: actions/checkout@v2
            - uses: docker://oskarstark/php-cs-fixer-ga:latest
              with:
                args: --config=.php-cs-fixer.php --diff
            - uses: peter-evans/create-pull-request@v4
              id: cpr
              with:
                  base: ${{ github.base_ref }}
                  token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: Apply php-cs-fixer changes as of ${{ github.base.sha }}
                  title: Fix coding standards in ${{ github.base_ref }} after merged by ${{ github.head_ref }}
                  branch: php-cs-fixer/${{ github.ref }}
                  assignees: ${{ github.actor }}
                  body: |
                    Please apply these changes on the ${{ github.head_ref }} branch to fix coding standard violations.
            - uses: unsplash/comment-on-pr@v1.2.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              if: steps.cpr.outputs.pr_number
              #continue-on-error: true # Will fail if not on PR
              with:
                  msg: |
                    @${{ github.actor }} Thank you for you contribution! Your changes will be reformatted (#${{ steps.cpr.outputs.pr_number }}) in order to assimilate with the repository's code style.   
