on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]

name: Create PRs for php-cs-fixer fixups

jobs:
    fix-cs:
        name: Fix CS violations
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2     
            - uses: docker://oskarstark/php-cs-fixer-ga:latest
              with:
                args: --config=.php-cs-fixer.php --diff
            - uses: peter-evans/create-pull-request@v4
              id: cpr
              if: github.event.pull_request && (github.event.pull_request.draft == false)
              with:
                  base: ${{ github.head_ref }}
                  token: ${{ secrets.GITHUB_TOKEN }}
                  commit-message: Apply php-cs-fixer changes as of ${{ github.head.sha }}
                  title: Fix coding standards in ${{ github.ref }} (HEAD: ${{ github.head_ref}})
                  branch: php-cs-fixer/${{ github.head_ref }}
                  assignees: ${{ github.actor }}
                  body: |
                    Please apply these changes on the ${{ github.head_ref }} branch to fix coding standard violations.

            - uses: unsplash/comment-on-pr@v1.2.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              if: steps.cpr.outputs.pr_number
              continue-on-error: true # Will fail if not on PR
              with:
                  msg: |
                    @${{ github.actor }} please apply the coding standard fixes from #${{ steps.cpr.outputs.pr_number }}
